package ca.http.myservlet.controller.command;

public enum CommandName {
	GOTOINDEXPAGE, GOTOLOGINPAGE, GOTOREGISTRATIONPAGE, GOTODROPMENUDETAILS, SAVENEWUSER, LOGINUSER, LOGOUTUSER,
	CITIESBYPROVINCE;

}
